name: "Run CI multi-OS"

on: pull_request

jobs:
  tests:
    runs-on: $${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.40.2
          cache: true
      - name: run test
        run: pixi run test
