name: "Run CI"

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
            pixi-version: v0.40.2
            cache: true
      - run: pixi run test
